//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int idnum { get; set; }
        public Nullable<int> list_idnum { get; set; }
        public string body { get; set; }
        public string writtenBy { get; set; }
    }
}
